name: Build
on:
  push:
    branches:
      - main
jobs:
  html-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Lint HTML files
        run: npx htmlhint **/*.html
